# Generated by Django 3.0.8 on 2020-08-25 16:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200825_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to=user.models.profile_pic_upload_path),
        ),
    ]
